server:
  port: 8000
spring:
  application:
    name: skins
  datasource:
    url: jdbc:mysql://localhost:3306/skingambleur
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
